env:
  node: true
  es6: true
  browser: true

extends:
  # https://github.com/yannickcr/eslint-plugin-react#configuration
  - eslint:recommended
  - plugin:react/recommended
  # https://prettier.io/docs/en/eslint.html#why-not-both
  - plugin:prettier/recommended

plugins:
  - react

parser: babel-eslint

parserOptions:
  ecmaFeatures:
    jsx: true

rules:
  no-console: warn